language: scala

notifications:
  email:
    recipients:
      - rinat.sabitov@gmail.com
    on_success: change
    on_failure: change
    
install:
    - pip install cookiecutter
script:
    - cookiecutter gh:histrio/sbt.g8 --no-input test
    - cd test 
    - sbt build
